import type { Metadata } from "next";
// import { ErrorWrapper } from "./error-wrapper";

// Metadata ensures content looks great when shared or indexed by search engines
// 2 ways to handle metadata in layout.tsx or page.tsx files:
// export a STATIC metadata object
// export a DYNAMIC generateMetaData function
// layout.tsx metadata applies to all pages while page.tsx metadata applies only to that page
// Page metadata overrides layout metadata for matching properties
// DOES NOT WORK ON "use client" PAGES
// searchParams does not work on layout.tsx
// : Metadata is Typescript
export const metadata: Metadata = {
  // Title can be a string or object
  // title: {
  //   default: "Next.js Tutorial",
  //   %s is a placeholder for a child page.tsx metadata.title
  //   template: "%s - Next.js Tutorial",
  // },
  title: "Next.js Tutorial",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {/* <ErrorWrapper>{children}</ErrorWrapper> */}
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
